In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
import os
import seaborn as sns
import joblib
from sklearn.model_selection import train_test_split
import gzip

In [2]:
df = pd.read_csv('reviews_guitars.csv')

In [3]:
df

,Rating,reviewerID,asin,reviewerName,unixReviewTime,category,description,title,brand,feature,rank,main_cat,similar_item,date,price,cat,review_text,rating_cat,time,clean_text
0,3,A2S6XHXPUOUDPV,B00004UE2D,aztec,1106092800,"['Musical Instruments', 'Guitars', 'Classical ...","['The Yamaha C40 is an affordable, classical g...",Yamaha C40 Full Size Nylon-String Classical Gu...,Yamaha,"['Designed for Beginners, with an Eye and Ear ...","['>#13,455 in Musical Instruments (See Top 100...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","July 21, 2000",$22.99,"Musical Instruments,Guitars,Classical & Nylon-...","Not bad, but not too good either I've tried th...",good,2005-01-19,not bad not good either try c number time alwa...
1,1,A1E8PWW106DRBE,B00004UE2D,Vasya,1096934400,"['Musical Instruments', 'Guitars', 'Classical ...","['The Yamaha C40 is an affordable, classical g...",Yamaha C40 Full Size Nylon-String Classical Gu...,Yamaha,"['Designed for Beginners, with an Eye and Ear ...","['>#13,455 in Musical Instruments (See Top 100...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","July 21, 2000",$22.99,"Musical Instruments,Guitars,Classical & Nylon-...",Everyone seems to get good instrumen I got hor...,bad,2004-10-05,everyone seehems get good instrumen get horrib...
2,5,AHY195S8N3XSJ,B00004UE2D,scorpio ari,1093651200,"['Musical Instruments', 'Guitars', 'Classical ...","['The Yamaha C40 is an affordable, classical g...",Yamaha C40 Full Size Nylon-String Classical Gu...,Yamaha,"['Designed for Beginners, with an Eye and Ear ...","['>#13,455 in Musical Instruments (See Top 100...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","July 21, 2000",$22.99,"Musical Instruments,Guitars,Classical & Nylon-...",Happy with my classy Yammy The C40 is my first...,good,2004-08-28,happy classy yammy c first guitar could not ha...
3,4,A29CUCGRX04TS8,B00004UE2D,Sailoil,1092614400,"['Musical Instruments', 'Guitars', 'Classical ...","['The Yamaha C40 is an affordable, classical g...",Yamaha C40 Full Size Nylon-String Classical Gu...,Yamaha,"['Designed for Beginners, with an Eye and Ear ...","['>#13,455 in Musical Instruments (See Top 100...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","July 21, 2000",$22.99,"Musical Instruments,Guitars,Classical & Nylon-...",What do you want in a Guitar? When you approac...,good,2004-08-16,want guitar approach purchase musical instrume...
4,5,A121WJCKYJ4T03,B00004UE2D,taka(Japanese,1080086400,"['Musical Instruments', 'Guitars', 'Classical ...","['The Yamaha C40 is an affordable, classical g...",Yamaha C40 Full Size Nylon-String Classical Gu...,Yamaha,"['Designed for Beginners, with an Eye and Ear ...","['>#13,455 in Musical Instruments (See Top 100...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","July 21, 2000",$22.99,"Musical Instruments,Guitars,Classical & Nylon-...",The cost performance of Yamaha is great. Ymaha...,good,2004-03-24,cost performance yamaha great ymaha instrument...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59043,3,A32JRLJZB0524,B01HJAABPM,MATT FUQUA,1519084800,"['Musical Instruments', 'Guitars', 'Electric G...",['JS Series Dinky Minion JS1X Electric Guitar ...,Jackson JS Series Dinky Minion JS1X Electric G...,Jackson,"['"" Body Body shape: Double cutaway Body type:...","['>#118,017 in Musical Instruments (See Top 10...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","June 25, 2016",NaN,"Musical Instruments,Guitars,Electric Guitars,S...",Finish on it was great. Fret board is awesome ...,good,2018-02-20,finish great fret board awesome fret look fini...
59044,5,A372NZN38894Q3,B01HJAABPM,Edward Dickson,1513814400,"['Musical Instruments', 'Guitars', 'Electric G...",['JS Series Dinky Minion JS1X Electric Guitar ...,Jackson JS Series Dinky Minion JS1X Electric G...,Jackson,"['"" Body Body shape: Double cutaway Body type:...","['>#118,017 in Musical Instruments (See Top 10...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","June 25, 2016",NaN,"Musical Instruments,Guitars,Electric Guitars,S...",AWESOME value for an introductory Student Guit...,good,2017-12-21,awesome value introductory student guitar purc...
59045,5,A3PRMKNDBK7A5Z,B01HJAABPM,Amazon Customer,1512086400,"['Musical Instruments', 'Guitars', 'Electric G...",['JS Series Dinky Minion JS1X Electric Guitar ...,Jackson JS Series Dinky Minion JS1X Electric G...,Jackson,"['"" Body Body shape: Double cutaway Body type:...","['>#118,017 in Musical Instruments (See Top 10...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","June 25, 2016",NaN,"Musical Instruments,Guitars,Electric Guitars,S...",Five Stars Great,good,2017-12-01,five star great
59046,1,A11RAZPTFUMAE3,B01HJAABPM,Psychodelic69,1496966400,"['Musical Instruments', 'Guitars', 'Electric G...",['JS Series Dinky Minion JS1X Electric Guitar ...,Jackson JS Series Dinky Minion JS1X Electric G...,Jackson,"['"" Body Body shape: Double cutaway Body type:...","['>#118,017 in Musical Instruments (See Top 10...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","June 25, 2016",NaN,"Musical Instruments,Guitars,Electric Guitars,S...",For a small guitar it's the biggest piece of c...,bad,2017-06-09,small guitar biggest piece crap world small gu...
59047,4,A87KD9VIW92X1,B01HJAABPM,Casey Hulon,1484006400,"['Musical Instruments', 'Guitars', 'Electric G...",['JS Series Dinky Minion JS1X Electric Guitar ...,Jackson JS Series Dinky Minion JS1X Electric G...,Jackson,"['"" Body Body shape: Double cutaway Body type:...","['>#118,017 in Musical Instruments (See Top 10...",Musical Instruments,"class=""a-bordered a-horizontal-stripes a-spa...","June 25, 2016",NaN,"Musical Instruments,Guitars,Electric Guitars,S...",... the one we received has dark shadows that ...,good,2017-01-10,one receive dark shadow look like poor spray w...

In [4]:
df['rat'] = df['rating_cat'].map({'good': 1, 'bad': 0})

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59048 entries, 0 to 59047
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rating          59048 non-null  int64
 1   reviewerID      59048 non-null  object
 2   asin            59048 non-null  object
 3   reviewerName    59044 non-null  object
 4   unixReviewTime  59048 non-null  int64
 5   category        59048 non-null  object
 6   description     59048 non-null  object
 7   title           59048 non-null  object
 8   brand           58483 non-null  object
 9   feature         59048 non-null  object
 10  rank            59048 non-null  object
 11  main_cat        59048 non-null  object
 12  similar_item    35380 non-null  object
 13  date            59044 non-null  object
 14  price           29338 non-null  object
 15  cat             59048 non-null  object
 16  review_text     59048 non-null  object
 17  rating_cat      59048 non-null  object
 18  time            59048 non-null  object
 19  clean_text      59045 non-null  object
 20  rat             59048 non-null  int64
dtypes: int64(3), object(18)
memory usage: 9.5+ MB

In [6]:
df.drop(['reviewerName','unixReviewTime','category','price','description','brand','feature','rank','main_cat','similar_item','date','cat','review_text','clean_text','time','rating_cat'], axis=1, inplace=True)

In [7]:
df

,Rating,reviewerID,asin,title,rat
0,3,A2S6XHXPUOUDPV,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
1,1,A1E8PWW106DRBE,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,0
2,5,AHY195S8N3XSJ,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
3,4,A29CUCGRX04TS8,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
4,5,A121WJCKYJ4T03,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
...,...,...,...,...,...
59043,3,A32JRLJZB0524,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1
59044,5,A372NZN38894Q3,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1
59045,5,A3PRMKNDBK7A5Z,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1
59046,1,A11RAZPTFUMAE3,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,0
59047,4,A87KD9VIW92X1,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1

In [8]:
df = df.rename(columns={'Rating': 'Rating','reviewerID': 'user_ID', 'asin': 'product_ID','title': 'product_name',
                                                 'rat': 'Rating_category' })

In [9]:
df

,Rating,user_ID,product_ID,product_name,Rating_category
0,3,A2S6XHXPUOUDPV,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
1,1,A1E8PWW106DRBE,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,0
2,5,AHY195S8N3XSJ,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
3,4,A29CUCGRX04TS8,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
4,5,A121WJCKYJ4T03,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
...,...,...,...,...,...
59043,3,A32JRLJZB0524,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1
59044,5,A372NZN38894Q3,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1
59045,5,A3PRMKNDBK7A5Z,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1
59046,1,A11RAZPTFUMAE3,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,0
59047,4,A87KD9VIW92X1,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1

In [10]:
df.isnull().any().any()

False

In [11]:
len(df['user_ID'].unique())

53467

In [12]:
counts1=df['user_ID'].value_counts() 
counts=df['product_ID'].value_counts()

In [13]:
counts1

AKYDGCKCY7H9F     46
A1QUIHLOSKDY7R    37
A1HV1D5EKO45GA    29
AZMHABTPXVLG3     28
AI1Y40T5QZLNU     27
                  ..
AFU771ME2DKX5      1
AOAHW7AVH8159      1
A5JAUM70HV4CD      1
A3LI7E5PT0CWL4     1
A38KN8X5MF1E65     1
Name: user_ID, Length: 53467, dtype: int64

In [14]:
counts

B000VSM4MS    2488
B002RXXOX8    1396
B006BC3K3A    1253
B005JPWNVU    1008
B0002GXZK4     696
              ...
B00B5PA1VC       1
B00FCAP60W       1
B007SXOFK8       1
B00DSNSO0O       1
B000B68WEO       1
Name: product_ID, Length: 7570, dtype: int64

In [15]:
df

,Rating,user_ID,product_ID,product_name,Rating_category
0,3,A2S6XHXPUOUDPV,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
1,1,A1E8PWW106DRBE,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,0
2,5,AHY195S8N3XSJ,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
3,4,A29CUCGRX04TS8,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
4,5,A121WJCKYJ4T03,B00004UE2D,Yamaha C40 Full Size Nylon-String Classical Gu...,1
...,...,...,...,...,...
59043,3,A32JRLJZB0524,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1
59044,5,A372NZN38894Q3,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1
59045,5,A3PRMKNDBK7A5Z,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1
59046,1,A11RAZPTFUMAE3,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,0
59047,4,A87KD9VIW92X1,B01HJAABPM,Jackson JS Series Dinky Minion JS1X Electric G...,1

In [16]:
ratings_sum = pd.DataFrame(df.groupby(['product_ID'])['Rating'].sum()).rename(columns = {'Rating': 'ratings_sum'})
top10 = ratings_sum.sort_values('ratings_sum', ascending = False).head(10)
top10

            ratings_sum
product_ID
B000VSM4MS         8645
B002RXXOX8         5888
B006BC3K3A         4184
B005JPWNVU         3981
B0002GXZK4         3108
B0092V7WJ0         2667
B000S8CX7M         2210
B00BMJ3N4S         2033
B00GCFCA00         1999
B00A6D50L0         1933

In [17]:
top10_popular=top10.merge(df,left_index = True, right_on = 'product_ID').drop_duplicates(
    ['product_ID', 'product_name'])[['product_ID', 'product_name','ratings_sum']]

In [18]:
top10_popular

,product_ID,product_name,ratings_sum
7690,B000VSM4MS,Crescent MG38-PK 38&quot; Acoustic Guitar Star...,8645
14204,B002RXXOX8,"Full Size Black Electric Guitar with Amp, Case...",5888
22593,B006BC3K3A,38&quot; PINK Acoustic Guitar Starters Beginne...,4184
20475,B005JPWNVU,Best Choice Products 41in Full Size Beginner E...,3981
3387,B0002GXZK4,Jasmine S34C NEX Acoustic Guitar,3108
26340,B0092V7WJ0,Fender FA-115 Acoustic Guitar Bundle with Gig ...,2667
6859,B000S8CX7M,First Act FG127 Acoustic Guitar,2210
29035,B00BMJ3N4S,Fender FA-100 Dreadnought Acoustic Guitar - Na...,2033
30552,B00GCFCA00,"Directly Cheap 6 String Acoustic Guitar Pack, ...",1999
27566,B00A6D50L0,Epiphone PPEG-EGL1VSCH1 Les Paul Electric Guit...,1933

In [21]:
traind, testd = train_test_split(ratingsd, test_size=0.30,random_state=42)

In [22]:
train = traind.values
test = testd.values

In [24]:
sparsity = float(len(train.nonzero()[0]))
sparsity /= (train.shape[0] * train.shape[1])
sparsity *= 100
print ('Sparsity: {:5.2f}%'.format(sparsity))

Sparsity:  0.01%

In [25]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(traind) 
print(svd.explained_variance_ratio_)  
print(svd.explained_variance_ratio_.sum())

#pm=pd.DataFrame(cosine_similarity(r_mat_tr))
#pm.head()
ctrain = cosine_similarity(r_mat_tr)

[0.04704396 0.03481267 0.01889512 0.01242274 0.01194272 0.01148861
 0.01095303 0.00924212 0.00793815 0.00732965 0.00707811 0.00691975
 0.00629098 0.00586197 0.0058488  0.00562493 0.0054237  0.00538393
 0.00535725 0.0050856  0.00487527 0.00462553 0.00439953 0.00439542
 0.00439399 0.00437048 0.0043418  0.00433629 0.00431898 0.0041123
 0.00409528 0.00400965 0.00384648 0.00371065 0.00371219 0.00365551
 0.00358196 0.00347847 0.00341145 0.0032683  0.00319341 0.00318235
 0.00297978 0.00276074 0.00272167 0.00270165 0.00265137 0.00263222
 0.00258075 0.00254217]
0.3398294416145927

In [26]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(testd) 
print(svd.explained_variance_ratio_)  
print(svd.explained_variance_ratio_.sum())

#pmtt=pd.DataFrame(cosine_similarity(r_mat_tr))
#print (pmtt[:2])
#pmtt.head()
ctest = cosine_similarity(r_mat_tr)

[0.04910612 0.04765717 0.03490507 0.02482195 0.02365257 0.02254404
 0.02051331 0.01956243 0.01729804 0.01688636 0.01252311 0.01192601
 0.00990798 0.00965874 0.00850538 0.00811748 0.00736859 0.00668131
 0.0066092  0.00648546 0.00605729 0.0060179  0.00596349 0.00576707
 0.00567917 0.00521596 0.00511802 0.00464373 0.00436811 0.00419721
 0.00410456 0.00402336 0.0040044  0.00394931 0.00392408 0.00382273
 0.00371508 0.00371114 0.00332217 0.00326726 0.00324794 0.00316151
 0.0030999  0.00302894 0.00289858 0.00284931 0.00269009 0.00251208
 0.00247941 0.0024595 ]
0.4840296250779524

In [28]:
from sklearn.metrics import mean_squared_error

def get_mse(pred, actual):
    # Ignore nonzero terms.
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)

In [29]:
print (' CF MSE: ' + str(get_mse(ctrain, ctest)))

 CF MSE: 0.2680909869967602

In [32]:
df = df.sort_values(by='Rating')
df = df.reset_index(drop=True)
count_users = df.groupby("user_ID", as_index=False).count()

In [33]:
count = df.groupby("product_ID", as_index=False).mean()

In [34]:
items_df = count[['product_ID']]
items_df.head()
print(len(items_df))

7570

In [35]:
users_df = count_users[['user_ID']]
users_df.head()
print(len(users_df))

53467

In [36]:
users_list = users_df.values
len(users_list)

53467

In [39]:
df_clean_matrix = df.pivot_table(index='product_ID', columns='user_ID', values='Rating').fillna(0)
df_clean_matrix = df_clean_matrix.T
R = (df_clean_matrix).values
R

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)
R_demeaned

array([[-0.0005284, -0.0005284, -0.0005284, ..., -0.0005284, -0.0005284,
        -0.0005284],
       [-0.0002642, -0.0002642, -0.0002642, ..., -0.0002642, -0.0002642,
        -0.0002642],
       [-0.0006605, -0.0006605, -0.0006605, ..., -0.0006605, -0.0006605,
        -0.0006605],
       ...,
       [-0.0005284, -0.0005284, -0.0005284, ..., -0.0005284, -0.0005284,
        -0.0005284],
       [-0.0009247, -0.0009247, -0.0009247, ..., -0.0009247, -0.0009247,
        -0.0009247],
       [-0.0006605, -0.0006605, -0.0006605, ..., -0.0006605, -0.0006605,
        -0.0006605]])

In [41]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned)

In [42]:
sigma = np.diag(sigma)

In [43]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = df_clean_matrix.columns)
preds_df['userID'] = users_df
preds_df.set_index('userID', inplace=True)
preds_df.head()

product_ID,B00004UE2D,B00005OWCU,B0000690ZK,B000071K5N,B00009J580,B00009KX28,B00009UVQZ,B0000DD4MC,B000189NIG,B000189NSQ,...,B01GV0PAJI,B01GV0PAYS,B01H1RGVGQ,B01H45D8IY,B01H47XO22,B01HB4YZC6,B01HDXK4FM,B01HG0FXAI,B01HH3KOP8,B01HJAABPM
userID,,,,,,,,,,,,,,,,,,,,,
A0017442UF327BYZCG7F,-0.000145,-0.000039,-0.000034,-0.000030,-0.000223,-0.000032,-0.000032,-0.000030,-0.000030,-0.000053,...,-0.000028,-0.000029,-0.000047,-0.000029,-0.000077,-0.000029,-0.000029,-0.000032,-0.000047,-0.000031
A0072193KFP6LUHKEXLT,-0.000043,-0.000015,-0.000014,-0.000013,-0.000050,-0.000014,-0.000014,-0.000013,-0.000013,-0.000019,...,-0.000013,-0.000013,0.001104,-0.000013,0.000668,-0.000013,-0.000013,-0.000015,-0.000018,-0.000014
A0137688I5EBPOFORHRY,0.000654,0.000658,0.000658,0.000657,0.000656,0.000658,0.000658,0.000658,0.000658,0.000657,...,0.000658,0.000658,0.000659,0.000658,0.000658,0.000658,0.000658,0.000658,0.000657,0.000658
A0138350SKSOOX32L0QL,0.000657,0.000661,0.000661,0.000661,0.000660,0.000661,0.000661,0.000661,0.000661,0.000660,...,0.000661,0.000661,0.000662,0.000661,0.000662,0.000661,0.000661,0.000661,0.000661,0.000661
A0160490ZS2UZODAMGC4,0.000267,0.000263,0.000263,0.000264,0.000266,0.000263,0.000263,0.000263,0.000263,0.000264,...,0.000263,0.000263,0.000263,0.000263,0.000263,0.000263,0.000263,0.000263,0.000263,0.000263

In [44]:
preds_df.shape

(53467, 7570)

In [48]:
def recommend_it(predictions_df, itm_df, original_ratings_df, num_recommendations=10,ruserId='A0017442UF327BYZCG7F'):
    
    # Get and sort the user's predictions
    sorted_user_predictions = predictions_df.loc[ruserId].sort_values(ascending=False)
    
    # Get the user's data and merge in the item information.
    user_data = original_ratings_df[original_ratings_df.user_ID == ruserId]
    user_full = (user_data.merge(itm_df, how = 'left', left_on = 'product_ID', right_on = 'product_ID').
                     sort_values(['Rating'], ascending=False)
                 )

    print ('User {0} has already purchased {1} items.'.format(ruserId, user_full.shape[0]))
    print ('Recommending the highest {0} predicted  items not already purchased.'.format(num_recommendations))
    
    # Recommend the highest predicted rating items that the user hasn't bought yet.
    recommendations = (itm_df[~itm_df['product_ID'].isin(user_full['product_ID'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'product_ID',
               right_on = 'product_ID').
         rename(columns = {ruserId: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )
    topk=recommendations.merge(original_ratings_df,left_index = True, right_on = 'product_ID',left_on='product_ID').drop_duplicates(
    ['product_ID', 'product_name'])[['product_ID', 'product_name']]

    return topk

In [49]:
recommend_it(preds_df, items_df, df, 5)

User A0017442UF327BYZCG7F has already purchased 1 items.
Recommending the highest 5 predicted  items not already purchased.

      product_ID                                       product_name
936   B009FKQS98  Davison Guitars Full Size Electric Bass Guitar...
3009  B000189YD0  Silvertone LB11 Bass Guitar and Amp Package, C...
574   B004BZU4OW   Rogue RA-090 Dreadnought Acoustic Guitar Natural
619   B00BMJ3N4S  Fender FA-100 Dreadnought Acoustic Guitar - Na...
413   B00GCFCA00  Directly Cheap 6 String Acoustic Guitar Pack, ...

In [52]:
recommend_it(preds_df, items_df, df, 5,'A1HV1D5EKO45GA')

User A1HV1D5EKO45GA has already purchased 29 items.
Recommending the highest 5 predicted  items not already purchased.

      product_ID                                       product_name
2103  B000S8CX7M                    First Act FG127 Acoustic Guitar
5427  B000RW0GT6                Seagull S6 Original Acoustic Guitar
700   B00BMJ3M44  Fender CD-60S Dreadnought Acoustic Guitar - Na...
414   B000P63U74  Martin Steel String Backpacker Travel Guitar w...
518   B001LNN30E   Cordoba C5 Acoustic Nylon String Classical Gu...